version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  main:
    jobs:
      - build


jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build Distro  
          command: poetry build
